#!/bin/bash

# módulo que instala (o desinstala) los paquetes especificados
# actualizando la caché de metadatos si así se indica

# argumentos:
#       "name": la lista con los nombres de los paquetes (obligatorio)
#       "state": "present"|"absent" (por defecto, "present")
#	"update-cache": "true"|"false" (por defecto, "false"; ignorado si "absent")

# valor devuelto:
#       0 OK con cambios
#       128 OK sin cambios
#       1 ejecución sin ser superusuario
#       2 error en argumentos
#       3 error algún paquete a instalar o desinstalar no existe
#       4 error en mandato que crea el usuario
#       5 error en mandato que elimina el usuario

test $(id -u) = 0 || exit 1 # debe ejecutarse como superusuario

. $(dirname $0)/prologue # incluye el prólogo

